# Generated by Django 3.1.7 on 2021-04-02 19:12

import backend.core.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSlideDynamica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Slug')),
                ('type_image', models.CharField(blank=True, choices=[('JPEG', 'jpeg'), ('PNG', 'png')], max_length=255, null=True, verbose_name='Tipo da imagem')),
                ('image', models.FileField(blank=True, null=True, storage=backend.core.storage.OverwriteStorage(location='_public/static'), upload_to='', verbose_name='Imagem')),
            ],
        ),
    ]
